name: Build and Release AutoClicker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: AutoClicker.sln
      Project_Path: Autoclicker/Autoclicker.csproj

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build project
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}

    - name: Publish as a single-file executable
      run: dotnet publish $env:Solution_Name --configuration ${{ matrix.configuration }} --output ./publish --self-contained true --runtime win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: ./publish/AutoClicker.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
