name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker
          path: publish

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: AutoClicker
          path: publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
